version: "3.3"

services:

  # MySQL
  db:
    container_name: "fastapi-db"
    build: ./docker/mysql
    restart: always
    tty: true
    env_file:
      - ./.envs/.local/.mysql
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    networks:
      - local-net

  # FastAPI
  api:
    links:
      - db
    container_name: "fastapi-api"
    environment:
      - MYSQL_HOST=fastapi-db
    env_file:
      - ./.envs/.local/.mysql
    build: ./docker/api
    command: /start
    ports:
      - "8000:8000"
    volumes:
      - ./code:/usr/src/server
    networks:
      - local-net
volumes:
  mysql-data:

networks:
  local-net:
    driver: bridge
